### ISSUE TITLE
Source map should not be emited for production

### ISSUE THREAD

**Issue by hvelarde** [simplesconsultoria/sc.recipe.staticresources#35]
It makes no sense to emit a source map for production code:
* https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map
* https://webpack.js.org/configuration/devtool/

![selection_023](https://user-images.githubusercontent.com/341393/45126069-dc342780-b147-11e8-94e6-c3d45beff455.png)

**Comment by rodfersou** [comment]
Looks like what we need is to use the **inline-source-maps** option https://webpack.js.org/configuration/devtool/#devtool

**Comment by rodfersou** [comment]
Or the **eval** option that is superfast.
