### ISSUE TITLE
Replace postcss-cssnext with postcss-preset-env

### ISSUE THREAD

**Issue by hvelarde** [simplesconsultoria/sc.recipe.staticresources#37]
[postcss-cssnext](http://cssnext.io/) is deprecated and we must use [postcss-preset-env](https://preset-env.cssdb.org/) instead:

https://moox.io/blog/deprecating-cssnext/

**Comment by rodfersou** [comment]
looks like need to update do webpack 4 to make it work https://medium.com/@jontorrado/working-with-webpack-4-es6-postcss-with-preset-env-and-more-93b3d77db7b2
