### ISSUE TITLE
Use SCSS by default

### ISSUE THREAD

**Issue by rodfersou** [simplesconsultoria/sc.recipe.staticresources#6]
- [x] Remove LESS
- [x] Add SCSS

**Comment by rodfersou** [comment]
Is it desirable to keep both LESS and SCSS configuration, and an option at buildout to select which one should be created in the default template?

@agnogueira @hvelarde comments please

**Comment by hvelarde** [comment]
no, let's use just SCSS.

**Comment by rodfersou** [comment]
Done here https://github.com/simplesconsultoria/sc.recipe.staticresources/pull/12/files
